name: Testing Github Actions

on:
  push: 
    branches: 
      - "main"

jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - uses: Mikael-RnD/setup-uipath@v2
        with:
          version: 24.12.9111.31003

      #- name : Get the uipath cli version
       # run : uipcli --version
        
     # - name : Get the dotnet version
      #  run : dotnet --version

      - name : Checkout the package
        uses : actions/checkout@v4
        with :
          path : test

      - name: Build the package
        run : uipcli package pack "D:/a/cicd/cicd/test" -o "D:/a/cicd/cicd/package" --autoVersion  --libraryOrchestratorApplicationId ${{secrets.ORCHESTRATOR_APPLICATION_ID}} --libraryOrchestratorApplicationSecret ${{secrets.ORCHESTRATOR_APPLICATION_SECRET}} --repositoryUrl ${{github.repositoryUrl}} --repositoryCommit ${{github.sha}} --repositoryBranch ${{github.ref}}
      
      - name: Upload the package to orchestrator
        run: uipcli package deploy "D:/a/cicd/cicd/package/" "https://cloud.uipath.com/" DefaultTenant --organizationUnit "SharedFeed" --accountForApp "persouatgski" --createProcess true --applicationId ${{secrets.ORCHESTRATOR_APPLICATION_ID}} --applicationSecret ${{secrets.ORCHESTRATOR_APPLICATION_SECRET}} --applicationScope "OR.Default"
     
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "D:/a/cicd/cicd/package"
          if-no-files-found: "error"

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag
        with:
          github-token: ${{github.token}}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "D:/a/cicd/cicd/package/"
          name: "Test Release"
          body: "Release body"
          tag: ${{steps.tag.outputs.new_tag}}

      - name: Echo output of release
        run: |
          echo "id : ${{steps.create_release.outputs.id}}"
          echo "html_url: ${{steps.create_release.outputs.html_url}}"
          echo "upload_url: ${{steps.create_release.outputs.upload_url}}"
        
