name: Testing Github Actions

on:
  push: 
    branches: 
      - "main"

jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - uses: Mikael-RnD/setup-uipath@v2
        with:
          version: 24.12.9111.31003

      #- name : Get the uipath cli version
       # run : uipcli --version
        
     # - name : Get the dotnet version
      #  run : dotnet --version

      - name : Checkout the package
        uses : actions/checkout@v4
        with :
          path : test

      - name: Build the package
        run : uipcli package pack "D:\a\PDF-Automation\PDF-Automation\test" -o "./root" --autoVersion  --libraryOrchestratorApplicationId ${{secrets.ORCHESTRATOR_APPLICATION_ID}} --libraryOrchestratorApplicationSecret ${{secrets.ORCHESTRATOR_APPLICATION_SECRET}} --repositoryUrl ${{github.repositoryUrl}} --repositoryCommit ${{github.sha}} --repositoryBranch ${{github.ref}}
        
